### PR TITLE
Added first api draft + data deployment

### LINKED ISSUE #36: create sprites for cifar10 image database
export cifar10 images as sprites

### PR DESCRIPTION
**Pull request by gfrogat**
closes #36 
closes #51

here's a first draft of the API, so you can work an the detail views.

The code is still a bit messy, but I'll rework it over the week (I initially thought that you should simply work on this branch so we don't mess up `develop`)

For setting up the `lmdb` database, you'll have to run the script `setup_lmdb.py` locally with `python2`.

For the `sqlite` part, just download the example db from our Google Drive folder and place it under `/malevo/data`.

Unfortunately the sqlite part does not properly work in Docker, due to (what I assume) filesystem rights. Maybe you can have a look at it.

### CODE REVIEW

**Comment by NMO13** [comment]
Please make sure that the circleci tests succeed.

**Comment by NMO13** [comment]
Seems like that PIL version 5.0.0 is invalid:
`Could not find a version that satisfies the requirement PIL==5.0.0 (from -r requirements_dev.txt (line 9)) (from versions: )`

**Comment by NMO13** [comment]
Good.
Another thing you always have to do when you write python code: you have to run _flake8_ before you commit.

_flake8_ runs in CircleCI and checks code quality metrics.
You need to install flake8 locally for the python version 2.7.

**Comment by NMO13** [comment]
> malevo@1.0.0-SNAPSHOT check /home/circleci/phovea
> flake8

./malevo/api.py:18:1: E402 module level import not at top of file
./malevo/api.py:19:1: E402 module level import not at top of file
./malevo/api.py:30:5: F841 local variable 'run_id' is assigned to but never used
./malevo/api.py:48:1: E265 block comment should start with '# '
./malevo/api.py:49:1: E265 block comment should start with '# '
./malevo/api.py:50:5: E265 block comment should start with '# '
./malevo/api.py:51:5: E265 block comment should start with '# '
./malevo/api.py:54:5: F841 local variable 'run_id' is assigned to but never used
./malevo/api.py:76:17: E231 missing whitespace after ','
./malevo/api.py:76:19: E231 missing whitespace after ','
./malevo/api.py:87:37: E226 missing whitespace around arithmetic operator
./malevo/api.py:87:43: E226 missing whitespace around arithmetic operator
./malevo/util.py:16:1: E302 expected 2 blank lines, found 1

**Comment by thinkh** [comment]
@gfrogat: I'm working with Anita on dockerizing the lmdb. I found the [ppc64le/lmdb](https://hub.docker.com/r/ppc64le/lmdb/) Docker image, which uses the the [mdb_load](http://www.lmdb.tech/doc/man1/mdb_load_1.html) script. However, it doesn't work with the example.db file you provided. Can you either say how we could use this command-line tool or export your LMDB in a format that we can import it again?

**Comment by anita-steiner** [comment]
has the database in the google drive all pictures in it and you don't have to run setup_lmdb.py or do you have to run it

**Comment by gfrogat** [comment]
the `example.db` is not an `lmdb` but a `sqlite` database

For generating the `lmdb` database there's the setup script.


This pull request should not be merged into the develop branch yet, and only exists that you can start to work on the image previews. I only created the pull request so it's easier to see my changes.

**Comment by anita-steiner** [comment]
ok and where is the lmdb database

**Comment by NMO13** [comment]
You dont have to create a PR to see changes. Using the comparison tool is enough to see code changes:
a

**Comment by gfrogat** [comment]
@NMO13 Holger asked me to create a pull request, so I created one.

@anita-steiner as mentioned in the description, please use the python script `setup_lmdb.py` to create it.

**Comment by thinkh** [comment]
> @NMO13 Holger asked me to create a pull request, so I created one.
Yes, because it is easier to track the discussion here.

@gfrogat I was able to create the LMDB files now. Next we will figure out how to use it within the Docker container.

**Comment by thinkh** [comment]
Quick-and-dirty image view to show that it works. However, there are still a few bugs to fix.

malevo-image-view

**Comment by thinkh** [comment]
@gfrogat Does the relationships in the example.db apply to a specific or all trainings/runs (i.e. phovea datasets)?

**Comment by thinkh** [comment]
I modified the `setup_lmdb.py` that it checks if the LMDB was already created and run only if necessary. At the moment I can setup the LMDB by logging into the Docker container and running the script:
```
docker ps # <container id>
docker exec -i -t <container id> /bin/bash
cd malevo/data/script/
python setup_lmdb.py
```
@anita-steiner Can you please find a way how to run the script when building the API container? I don't know how to modify the `deploy/docker-compose.partial.yml`.

Another thing we have to solve is the download of the SQLite `example.db` (I suggest to rename this according to @gfrogat answer). If it doesn't contain sensitive data we can use a public link and download the file with the setup_script.py.

**Comment by gfrogat** [comment]
I created a new database `rundata.db` that contains the `run_id`, `img_id`, `epoch_id`, `ground_truth` and `predicted` columns, for all the runs for which we also have the softmax values.

Had to remove the `vgg16` data because it's incomplete

**Comment by thinkh** [comment]
@anita-steiner Thanks for your commits.

Ad 1: Yes, at the moment the phovea_product.json in malevo_product#develop points to this develop branch. You can change the dependency to the malevo repo temporary to this branch to test the deployment. Then you can also test the product/file download by setting up a new workspace with `yo phovea:setup-workspace malevo_product -b develop`. Later we can switch back to the develop branch.

You don't need to generate the LMDB files again. They are available in the Google Drive as well. Upload them to the S3 Bucket and reference them in the product as well.

Ad 2: Yes, sounds fine to me. If you can do this that would be good. Is it a change inside the malevo repo or in phovea_server?

**Comment by thinkh** [comment]
Delete the malevo_cifar10_example.db. 
The LMDB consists of the malevo_cifar10_data.mdb and malevo_cifar10_lock.mdb and contains the images. The malevo_cifar10_rundata.db is the SQLite DB and contains the relationship between images and classes. All files are used by the `api.py` file from this branch. You'll find the paths you need to change there.

**Comment by anita-steiner** [comment]
ok api.py ist geändert

**Comment by thinkh** [comment]
@anita-steiner Thanks for you changes. I will try them.

**Comment by thinkh** [comment]
Testing the deployment of this branch shows that the API calls are not available, due to insufficient product information.

The error/question is reported here: https://github.com/phovea/generator-phovea/issues/135. As soon as this is solved, we can try the deployment again.

**Comment by thinkh** [comment]
The deployment with the images is finally working. 

@NMO13 Please resolve the conflicts and merge this branch into the develop branch.

**Comment by NMO13** [comment]
Thank you guys! Awesome work!

**Pull request merged**
